SHELL = /bin/bash

# Python extras, from setup.py
PY_EXTRA_DEV = dev

# For conda initialisation
CONDA_ACTIVATE = source $$(conda info --base)/etc/profile.d/conda.sh ; conda activate ; conda activate
